import sys
import os

# Add root to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from enclave.sif_parser import SIFParser

def verify_dashboard_sif():
    file_path = "enclave_gemini/storage/private/dashboard_concept.sif"
    print(f"Verifying {file_path}...")
    
    try:
        with open(file_path, "r") as f:
            content = f.read()
            
        graph = SIFParser.parse(content)
        print(f"  [PASS] Successfully parsed graph '{graph.id}' generated by '{graph.generator}'.")
        print(f"  Nodes: {len(graph.nodes)}")
        print(f"  Edges: {len(graph.edges)}")
        
        for edge in graph.edges:
            print(f"    {edge.source} --[{edge.relation}]--> {edge.target}")
            
    except Exception as e:
        print(f"  [FAIL] Verification failed: {e}")

if __name__ == "__main__":
    verify_dashboard_sif()
